name: Deploy Frontend

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key and environment variables
        run: |
          mkdir -p ~/.ssh

          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "KEY=${{ secrets.PROD_EC2_SSH_KEY }}" >> $GITHUB_ENV
            echo "HOST=$PROD_EC2_HOST" >> $GITHUB_ENV
            echo "USER=$PROD_EC2_USER" >> $GITHUB_ENV
            echo "FOLDER=client-xplodivity" >> $GITHUB_ENV
            echo "PM2_APP_NAME=client-xplodivity" >> $GITHUB_ENV
          else
            echo "KEY=${{ secrets.DEV_EC2_SSH_KEY }}" >> $GITHUB_ENV
            echo "HOST=$DEV_EC2_HOST" >> $GITHUB_ENV
            echo "USER=$DEV_EC2_USER" >> $GITHUB_ENV
            echo "FOLDER=client-xplodivity" >> $GITHUB_ENV
            echo "PM2_APP_NAME=client-xplodivity" >> $GITHUB_ENV
          fi

          chmod 600 ~/.ssh/xplodivity_ci_cd_dev_ec2_key
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts
        env:
          PROD_EC2_SSH_KEY: ${{ secrets.PROD_EC2_SSH_KEY }}
          DEV_EC2_SSH_KEY: ${{ secrets.DEV_EC2_SSH_KEY }}
          PROD_EC2_HOST: ${{ secrets.PROD_EC2_HOST }}
          DEV_EC2_HOST: ${{ secrets.DEV_EC2_HOST }}
          PROD_EC2_USER: ${{ secrets.PROD_EC2_USER }}
          DEV_EC2_USER: ${{ secrets.DEV_EC2_USER }}

      - name: Deploy via SSH
        run: |
          ssh $USER@$HOST << EOF
            cd /home/$USER/$FOLDER
            git fetch origin
            git checkout ${GITHUB_REF##*/}
            git reset --hard origin/${GITHUB_REF##*/}
            npm install
            npm run build
            pm2 restart $PM2_APP_NAME ||  pm2 restart $PM2_APP_NAME || pm2 start npm --name "$PM2_APP_NAME" -- run start -- -p 3000
          EOF
