name: Deploy Frontend

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key and environment variables
        run: |
          mkdir -p ~/.ssh

          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "$PROD_EC2_SSH_KEY" > ~/.ssh/id_rsa
            export HOST=$PROD_EC2_HOST
            export USER=$PROD_EC2_USER
            echo "HOST=$HOST" >> $GITHUB_ENV
            echo "USER=$USER" >> $GITHUB_ENV
          else
            echo "$DEV_EC2_SSH_KEY" > ~/.ssh/id_rsa
            export HOST=$DEV_EC2_HOST
            export USER=$DEV_EC2_USER
            echo "HOST=$HOST" >> $GITHUB_ENV
            echo "USER=$USER" >> $GITHUB_ENV
          fi

          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts
        env:
          PROD_EC2_SSH_KEY: ${{ secrets.PROD_EC2_SSH_KEY }}
          DEV_EC2_SSH_KEY: ${{ secrets.DEV_EC2_SSH_KEY }}
          PROD_EC2_HOST: ${{ secrets.PROD_EC2_HOST }}
          DEV_EC2_HOST: ${{ secrets.DEV_EC2_HOST }}
          PROD_EC2_USER: ${{ secrets.PROD_EC2_USER }}
          DEV_EC2_USER: ${{ secrets.DEV_EC2_USER }}

      - name: Deploy via SSH
        run: |
          ssh $USER@$HOST << EOF
            cd /home/$USER/$FOLDER
            git checkout ${GITHUB_REF##*/}
            git pull origin ${GITHUB_REF##*/}
            npm install
            npm run build
            pm2 stop $PM2_APP_NAME
            pm2 start npm --name "$PM2_APP_NAME" -- run start -- -p 3000
          EOF
